RentACarProject/RentACarAdminPanel/Models/ErrorViewModel.cs
using System;

namespace RentACarAdminPanel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RentACarProject/RentACarAdminPanel/Controllers/CarController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Update;
using RentACarBusiness.Abstract;
using RentACarBusiness.Validations;
using RentACarDataAccess;
using RentACarEntities.Concrete;
using System.Linq;

namespace RentACarAdminPanel.Controllers
{
    public class CarController : Controller
    {
        Context c = new Context();

        ICarsService carService;

        public CarController(ICarsService carService)
        {
            this.carService = carService;
        }

        //GET ALL

        [Authorize(Roles = "admin")]
        public IActionResult GetAll()
        {
            var result = carService.GetCarsWithModels();
            return View(result);
        }

        //ADD CAR

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Cars car)
        {
            CarsValidationRules carValidator = new CarsValidationRules();
            ValidationResult result = carValidator.Validate(car);

            if (result.IsValid)
            {
                carService.AddCar(car);
                return RedirectToAction("GetAll");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        //UPDATE CAR

        public IActionResult Update(int id)
        {
            var result = carService.GetCarById(id);
            return View(result);
        }

        [HttpPost]
        public IActionResult Update(Cars car)
        {
            CarsValidationRules carValidator = new CarsValidationRules();
            ValidationResult result = carValidator.Validate(car);
            if (result.IsValid)
            {
                carService.UpdateCar(car);
                return RedirectToAction("GetAll");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        //DELETE CAR

        public IActionResult Delete(int id)
        {
            var result = c.Cars.FirstOrDefault(x => x.carID == id);
            carService.DeleteCar(result);
            return RedirectToAction("GetAll");
        }
    }
}

RentACarProject/RentACarAdminPanel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RentACarAdminPanel.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RentACarAdminPanel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RentACarProject/RentACarAdminPanel/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using RentACarBusiness.Abstract;
using RentACarDataAccess;
using RentACarEntities.Concrete;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RentACarAdminPanel.Controllers
{
    public class LoginController : Controller
    {
        Context c = new Context();

        private readonly IUserService userService;
        public LoginController(IUserService userService)
        {
            this.userService = userService;
        }

        //LOGIN

        public IActionResult Login(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Users user)
        {
            var values = c.Users.FirstOrDefault(x => x.userEmail == user.userEmail && x.password == user.password);
            if(values != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, values.userEmail),
                    new Claim(ClaimTypes.Role, values.userRole)
                };

                var identity = new ClaimsIdentity(claims, "Login");

                ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(principal);


                if (TempData["returnUrl"] != null)
                {
                    if (Url.IsLocalUrl(TempData["returnUrl"].ToString()))
                    {
                        return Redirect(TempData["returnUrl"].ToString());
                    }
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }

        //LOG OUT

        public IActionResult LogOut()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Login", "Login");
        }

        //CREATE ACCOUNT

        public IActionResult CreateAccount()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateAccount(Users user)
        {
            userService.AddUser(user);
            return RedirectToAction("Login");
        }

        //INDEX
        public IActionResult Index()
        {
            return View();
        }
    }
}

RentACarProject/RentACarAdminPanel/Views/Car/Add.cshtml
<div class="card">
    <div class="card-body">
        <h4 class="card-title">
            Product Information
        </h4>
        <form asp-action="Add" asp-controller="Car" method="post">
            <div class="mb-3 mt-5">
                <label for="carName" class="form-label">Car Name</label>
                <input type="text" class="form-control" name="carName">
            </div> 
            <div class="mb-3">
                <label for="brandID" class="form-label">Model ID</label>
                <input type="text" class="form-control" name="brandID">
            </div>
            <div class="mb-3">
                <label for="quantity" class="form-label">Quantity</label>
                <input type="number" class="form-control" name="quantity">
            </div>
            <div class="mb-3">
                <label for="doors" class="form-label">Doors</label>
                <input type="text" class="form-control" name="doors">
            </div>
            <div class="mb-3">
                <label for="carPrice" class="form-label">Price</label>
                <input type="number" class="form-control" name="carPrice">
            </div>
            <div class="mb-3">
                <label for="categoryID" class="form-label">Category ID</label>
                <input type="text" class="form-control" name="categoryID">
            </div>

            <button type="submit" class="btn btn-primary">ADD CAR</button>
        </form>

    </div>
</div>

RentACarProject/RentACarAdminPanel/Views/Car/GetAll.cshtml
@using RentACarEntities.Concrete
@model List<Cars>


<div class="card">
    <div class="card-body">
        <h4 class="card-title">
            CAR LIST PAGE
        </h4>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Car ID</th>
                        <th>Car Name</th>
                        <th>Car Price</th>
                        <th>Quantity</th>
                        <th>Doors</th>
                        <th>Brand Name</th>
                        <th>Category ID</th>
                        <th>
                            <a href="/Car/Add" class="btn  btn-success text-white ml-2">
                                ADD
                            </a>
                        </th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>@item.carID</td>
                            <td>@item.carName</td>
                            <td>@item.carPrice</td>
                            <td>@item.quantity</td>
                            <td>@item.doors</td>
                            <td>@item.Brand.brandName</td>
                            <td>@item.categoryID</td>
                            <td>
                                <a asp-controller="Car" asp-action="Delete" asp-route-id="@item.carID" class="btn  btn-danger text-white ml-2">
                                     <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                                </svg>
                                </a>
                                <a asp-controller="Car" asp-action="Update" asp-route-id="@item.carID" class="btn  btn-warning text-white ml-2">
                                     <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                </svg>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                }

            </table>
        </div>
    </div>
</div>

RentACarProject/RentACarAdminPanel/Views/Car/Update.cshtml
@using RentACarEntities.Concrete
@model RentACarEntities.Concrete.Cars

<div class="card">
    <div class="card-body">
        <h4 class="card-title">
            PRODUCT UPDATE PAGE
        </h4>
        <form asp-action="Update" asp-controller="Car" method="post">
            <div style="display:none" class="mb-3">
                <label for="carId" class="form-label">Car ID</label>
                <input readonly asp-for="carID" type="number" class="form-control">
            </div>
            <div class="mb-3">
                <label for="carName" class="form-label">Car Name</label>
                <input asp-for="carName" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label for="brandID" class="form-label">Brand ID</label>
                <input type="number" class="form-control" asp-for="brandID">
            </div>
            <div class="mb-3">
                <label for="Quantity" class="form-label">Quantity</label>
                <input type="number" class="form-control" asp-for="quantity">
            </div>
            <div class="mb-3">
                <label for="vehicleType" class="form-label">Doors</label>
                <input type="number" class="form-control" asp-for="doors">
            </div>
            <div class="mb-3">
                <label for="Luggage" class="form-label">Luggage</label>
                <input type="number" class="form-control" asp-for="carPrice">
            </div>
            <div class="mb-3">
                <label for="categoryId" class="form-label">Category ID</label>
                <input type="number" class="form-control" asp-for="categoryID">
            </div>
            <button type="submit" class="btn btn-primary">UPDATE PRODUCT</button>
        </form>
    </div>
</div>

RentACarProject/RentACarAdminPanel/Views/Home/Index.cshtml
<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>150</h3>

                    <p>New Orders</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>53<sup style="font-size: 20px">%</sup></h3>

                    <p>Bounce Rate</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>44</h3>

                    <p>User Registrations</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>65</h3>

                    <p>Unique Visitors</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-7 connectedSortable">
            <!-- Custom tabs (Charts with tabs)-->
            <div class="card">
                <div class="card-header ui-sortable-handle" style="cursor: move;">
                    <h3 class="card-title">
                        <i class="fas fa-chart-pie mr-1"></i>
                        Sales
                    </h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills ml-auto">
                            <li class="nav-item">
                                <a class="nav-link active" href="#revenue-chart" data-toggle="tab">Area</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#sales-chart" data-toggle="tab">Donut</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <div class="tab-content p-0">

                        <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 300px;">
                            <div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                            <canvas id="revenue-chart-canvas" height="600" style="height: 300px; display: block; width: 387px;" width="774" class="chartjs-render-monitor"></canvas>
                        </div>
                        <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;">
                            <canvas id="sales-chart-canvas" height="0" style="height: 0px; display: block; width: 0px;" width="0" class="chartjs-render-monitor"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card -->
        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        <section class="col-lg-5 connectedSortable">

            <!-- Map card -->
            <div class="card bg-gradient-primary">
                <div class="card-header border-0">
                    <h3 class="card-title">
                        <i class="fas fa-map-marker-alt mr-1"></i>
                        Visitors
                    </h3>
                    <!-- card tools -->
                    <div class="card-tools">
                        <button type="button" class="btn btn-primary btn-sm daterange" title="Date range">
                            <i class="far fa-calendar-alt"></i>
                        </button>
                        <button type="button" class="btn btn-primary btn-sm" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                    <!-- /.card-tools -->
                </div>
                <div class="card-body">
                    <div id="world-map" style="height: 250px; width: 100%;"></div>
                </div>
                <!-- /.card-body-->
                <div class="card-footer bg-transparent">
                    <div class="row">
                        <div class="col-4 text-center">
                            <div id="sparkline-1"></div>
                            <div class="text-white">Visitors</div>
                        </div>
                        <!-- ./col -->
                        <div class="col-4 text-center">
                            <div id="sparkline-2"></div>
                            <div class="text-white">Online</div>
                        </div>
                        <!-- ./col -->
                        <div class="col-4 text-center">
                            <div id="sparkline-3"></div>
                            <div class="text-white">Sales</div>
                        </div>
                        <!-- ./col -->
                    </div>
                    <!-- /.row -->
                </div>
            </div>
            <!-- /.card -->
            <!-- /.card -->
        </section>
        <!-- right col -->
    </div>
    <!-- /.row (main row) -->
</div><!-- /.container-fluid -->
<!-- /.content -->

RentACarProject/RentACarAdminPanel/Views/Login/CreateAccount.cshtml
@{
    Layout = null;
}
<!--===============================================================================================-->
<link rel="icon" type="image/png" href="~/assets/images/icons/favicon.ico" />
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/css/util.css">
<link rel="stylesheet" type="text/css" href="~/assets/css/main.css">
<!--===============================================================================================-->


<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100" style="background:#ac96df94; padding: 100px 130px 33px 95px; width:70%">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="~/assets/images/img-01.png" alt="IMG">
            </div>

            <form class="login100-form validate-form" asp-action="CreateAccount" asp-controller="Login" method="post">
                <span class="login100-form-title">
                    Hesap Oluşturunuz
                </span>

                <div class="wrap-input100 validate-input">
                    <input class="input100" type="email" name="userEmail" placeholder="Email">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input">
                    <input class="input100" type="password" name="password" placeholder="Password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input">
                    <input class="input100" type="text" name="userRole" placeholder="Role">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn">
                        Create
                    </button>
                </div>

                <div class="text-center p-t-12">
                    <span class="txt1">
                        Forgot
                    </span>
                    <a class="txt2" href="#">
                        Username / Password?
                    </a>
                </div>

                <div class="text-center p-t-136" style="padding-top: 90px">
                    <a class="txt2" href="/Login/Login">
                        Have an account?
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>




<!--===============================================================================================-->
<script src="~/assets/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/assets/vendor/bootstrap/js/popper.js"></script>
<script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/assets/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/assets/vendor/tilt/tilt.jquery.min.js"></script>
<script>
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>
<!--===============================================================================================-->
<script src="~/assets/js/main.js"></script>

RentACarProject/RentACarAdminPanel/Views/Login/Login.cshtml
@{
    Layout = null;
}
<!--===============================================================================================-->
<link rel="icon" type="image/png" href="~/assets/images/icons/favicon.ico" />
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assets/css/util.css">
<link rel="stylesheet" type="text/css" href="~/assets/css/main.css">
<!--===============================================================================================-->


<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100" style="background:#ac96df94; padding: 100px 130px 33px 95px; width:70%">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="~/assets/images/img-01.png" alt="IMG">
            </div>

            <form class="login100-form validate-form" asp-action="Login" asp-controller="Login" method="post">
                <span class="login100-form-title">
                    Giriş Yapınız
                </span>

                <div class="wrap-input100 validate-input">
                    <input class="input100" id="useremail" type="email" name="userEmail" placeholder="Email">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input">
                    <input class="input100" type="password" name="password" placeholder="Password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="container-login100-form-btn">
                    <button type="submit" id="login" onclick="degistir()" class="login100-form-btn">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-12">
                    <span class="txt1">
                        Forgot
                    </span>
                    <a class="txt2" href="#">
                        Username / Password?
                    </a>
                </div>

                <div class="text-center p-t-136" style="padding-top: 90px">
                    <a class="txt2" href="/Login/CreateAccount">
                        Create your Account
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>




<!--===============================================================================================-->
<script src="~/assets/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/assets/vendor/bootstrap/js/popper.js"></script>
<script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/assets/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/assets/vendor/tilt/tilt.jquery.min.js"></script>
<script>
    $('.js-tilt').tilt({
        scale: 1.1
    })

</script>
<!--===============================================================================================-->
<script src="~/assets/js/main.js"></script>